# Site settings
title: Spark Embedded
email: team@sparkembedded.com
url: https://github.com/Spark-Embedded/
description: "Spark Embedded, LLC"
keywords: "embedded development, firmware, engineering"
meta_author: Steinfadt Bailey

# Google webmaster tools
#google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:        # #31E042
  primary: 32cfe0 #80B3FF
  primary-rgb: "50,207,224" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Header settings
header:
  headline_line1: "Expert Partners for"
  headline_line2: "Complex Embedded Systems"
  skills_line1: "Professional Consulting and Rapid Development:"
  skills_line2: "Firmware • Modeling & Simulation • HIL Test Systems"
  button_text: "Explore Our Services"

# Footer settings
footer:
  copyright: Spark Embedded, LLC
  location:
    title: "Our Home"
    membership_text: "A Proud Member Of"
    membership_url: "https://www.maplestudios.com/"
    membership_logo: "/img/maple_studios_logo.png"
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/Spark-Embedded/
  - title: linkedin
    url: https://www.linkedin.com/company/spark-embedded/

# Postal address (add as many lines as necessary)
address:
  - line: "1207 Maple Street"
  - line: "West Des Moines, IA 50265"

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

collections:
  - what_we_do
  - experiences
