# Site settings
title: Spark Embedded
email: team@sparkembedded.com
url: https://github.com/Spark-Embedded/
description: "Spark Embedded, LLC"
keywords: "embedded development, firmware, engineering"
meta_author: Steinfadt Bailey

# Google webmaster tools
#google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:       
  primary: 00aa4fff # logo green
  primary-rgb: "0,170,79" # logo green 
  secondary: 000222ff # dark blue
  secondary-dark: 000222ff # dark blue
  # logo blue 74e2f7ff

# Header settings
header:
  headline_line1: "Expert Partners for"
  headline_line2: "Complex Embedded Systems"
  skills_line1: "Professional Consulting and Rapid Development:"
  skills_line2: "Firmware • Modeling & Simulation • HIL Test Systems"
  button_text: "Explore Our Services"

# Add the new founders section
founders:
  - name: "Bailey Steinfadt, Co-Founder"
    icon: "fa-code"
    bio: "With nearly 15 years of industry experience, Bailey is a firmware engineer with a passion for helping companies launch and improve their embedded systems teams. Before co-founding Spark Embedded, she successfully ran her own consultancy, Stone Path Engineering, where she provided firmware and process consulting. An active leader in the local tech community, Bailey was recognized as a 'Women of Innovation' Rising Star Award Finalist and is passionate about community education, having served as an instructor and director for the Des Moines Maker Space (Area515). She holds a B.S. in Computer Engineering from Iowa State University."
    linkedin_url: "https://www.linkedin.com/in/bailey-steinfadt/"

  - name: "William Griffin, Co-Founder"
    icon: "fa-tachometer"
    bio: "Prior to co-founding Spark Embedded, William spent nearly two decades contributing to and leading engineering teams developing and testing embedded controls for off-highway vehicles. From utilizing model-based system design (MBSD) to develop models of control software and physical systems, to architecting advanced Hardware-in-the-Loop (HIL) simulators, his experience spans a large swath of the product development lifecycle. He is passionate about building high-performing, collaborative engineering teams as well as developing programs to raise the engineering craftsmanship across organizations. William holds a Professional Science Master’s degree in Applied Physics from the University of Northern Iowa."
    linkedin_url: "https://www.linkedin.com/in/griffinwilliam/"

# Footer settings
footer:
  copyright: Spark Embedded, LLC
  location:
    title: "Our Home"
    membership_text: "A Proud Member Of"
    membership_url: "https://www.maplestudios.com/"
    membership_logo: "/img/maple_studios_logo.png"
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/Spark-Embedded/
  - title: linkedin
    url: https://www.linkedin.com/company/sparkembedded/

# Postal address (add as many lines as necessary)
address:
  - line: "1207 Maple Street"
  - line: "West Des Moines, IA 50265"

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""

collections:
  - what_we_do
  - community_engagements
